server:
  port: 8080
  servlet:
    context-path: /erp

spring:
  application:
    name: erp
  datasource:
    url: jdbc:postgresql://localhost:5432/erp-dev-db
    username: postgres
    password: 11229800
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: erp_v1
        hbm2ddl:
          auto: update
    show-sql: true
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always